version: "3.3"
services:
  nexus:
    image: sonatype/nexus3:3.80.0
    container_name: nexus3
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 8081:8081
    volumes:
      - ./data:/nexus-data

