version: '3.3'

services:
  registry:
    container_name: registry
    restart: always
    image: registry:3.0
    ports:
      - 5000:5000
    volumes:
      - ./config/config.yml:/etc/docker/registry/config.yml:ro
      - ./data:/var/lib/registry:rw
  #environment:
    #- "STANDALONE=true"
    #- "MIRROR_SOURCE=https://registry-1.docker.io"
    #- "MIRROR_SOURCE_INDEX=https://index.docker.io"
  web:
    image: konradkleine/docker-registry-frontend:v2
    restart: always
    ports:
    - 80:80
    environment:
    - ENV_DOCKER_REGISTRY_HOST=192.168.1.143
    - ENV_DOCKER_REGISTRY_PORT=5000
