concurrent = 10
check_interval = 0
connection_max_age = "15m0s"
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "docker-runner"
  tag_list = ["docker"]
  url = "http://192.168.110.37"
  id = 1
  token = "glrt-bzoxCnA6MQp0OjMKdToyhe5Q8xCqiWbhiViiDb5j2hA.170rcz79y"
  token_obtained_at = 2025-05-23T07:16:35Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    insecure_registries = ["192.168.110.40:5000"]
    volumes = ["/var/run/docker.sock:/var/run/docker.sock", "/cache"]
    tls_verify = false
    image = "docker:24.0.9"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    shm_size = 0
    network_mtu = 0

